services:
  db:
    container_name: database
    image: postgres:16-bookworm@sha256:sha256:3daa88ea6b4f430fa93bec541be8e295f021bb399929d75d2b768d8b9778f7cd
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [trascen]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    container_name: nextjs
    build: ./requirements/app
    restart: unless-stopped
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - user_uploads:/app/uploads
    networks: [trascen]

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: unless-stopped
    depends_on:
      - app
    ports:
      - "443:443"
    volumes:
      - user_uploads:/app/uploads:ro
    networks: [trascen]

volumes:
  db_data:
  user_uploads:

networks:
  trascen:
    driver: bridge
